// Generated by gencpp from file apriltag_detection/AprilTagDistance.msg
// DO NOT EDIT!


#ifndef APRILTAG_DETECTION_MESSAGE_APRILTAGDISTANCE_H
#define APRILTAG_DETECTION_MESSAGE_APRILTAGDISTANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace apriltag_detection
{
template <class ContainerAllocator>
struct AprilTagDistance_
{
  typedef AprilTagDistance_<ContainerAllocator> Type;

  AprilTagDistance_()
    : distance(0.0)  {
    }
  AprilTagDistance_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> const> ConstPtr;

}; // struct AprilTagDistance_

typedef ::apriltag_detection::AprilTagDistance_<std::allocator<void> > AprilTagDistance;

typedef boost::shared_ptr< ::apriltag_detection::AprilTagDistance > AprilTagDistancePtr;
typedef boost::shared_ptr< ::apriltag_detection::AprilTagDistance const> AprilTagDistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apriltag_detection::AprilTagDistance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::apriltag_detection::AprilTagDistance_<ContainerAllocator1> & lhs, const ::apriltag_detection::AprilTagDistance_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::apriltag_detection::AprilTagDistance_<ContainerAllocator1> & lhs, const ::apriltag_detection::AprilTagDistance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace apriltag_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::apriltag_detection::AprilTagDistance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apriltag_detection/AprilTagDistance";
  }

  static const char* value(const ::apriltag_detection::AprilTagDistance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n"
;
  }

  static const char* value(const ::apriltag_detection::AprilTagDistance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AprilTagDistance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apriltag_detection::AprilTagDistance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apriltag_detection::AprilTagDistance_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRILTAG_DETECTION_MESSAGE_APRILTAGDISTANCE_H
